<?php

namespace MfoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CalcConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalcConfigRepository extends EntityRepository
{
}
