<?php

namespace MfoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MicrofinanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MicrofinanceRepository extends EntityRepository
{
}
