<?php

namespace Taxi\LegionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AbonentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbonentsRepository extends EntityRepository
{
}
