<?php

namespace Taxi\LegionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DiscountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiscountRepository extends EntityRepository
{
}
