<?php

namespace Site\BackendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NewsPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsPostRepository extends EntityRepository
{
}
