# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

  encoders:
      FOS\UserBundle\Model\UserInterface: sha512

  role_hierarchy:
      ROLE_SUPER_ADMIN: ROLE_SUPER_ADMIN
      ROLE_MANAGER:     ROLE_MANAGER
      ROLE_DRIVER:      ROLE_DRIVER

  providers:
      fos_userbundle:
          id:           fos_user.user_provider.username

  firewalls:
      main:
          pattern: ^/
          form_login:
              provider: fos_userbundle
              csrf_provider: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
          logout:       true
          anonymous:    true

  access_control:
      - { path: ^/login$,        role: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/users,         role: ROLE_SUPER_ADMIN }
      - { path: ^/users/.*,      role: ROLE_SUPER_ADMIN }
      - { path: ^/tariffs,       role: ROLE_SUPER_ADMIN }
      - { path: ^/tariffs/.*,    role: ROLE_SUPER_ADMIN }
      - { path: ^/drivers,       role: ROLE_SUPER_ADMIN }
      - { path: ^/drivers/.*,    role: ROLE_SUPER_ADMIN }
      - { path: ^/logbook,       role: ROLE_SUPER_ADMIN }
      - { path: ^/logbook/.*,    role: ROLE_SUPER_ADMIN }
      - { path: ^/type-order,    role: ROLE_SUPER_ADMIN }
      - { path: ^/type-order/.*, role: ROLE_SUPER_ADMIN }
      - { path: ^/area,          role: ROLE_SUPER_ADMIN }
      - { path: ^/area/.*,       role: ROLE_SUPER_ADMIN }
      - { path: ^/discount,      role: ROLE_SUPER_ADMIN }
      - { path: ^/discount/.*,   role: ROLE_SUPER_ADMIN }
      - { path: ^/profile/.*,    role: ROLE_SUPER_ADMIN }
      - { path: ^/references,    role: ROLE_MANAGER }

